### ISSUE TITLE
For InputIcon with Lucide icons, size "sm" seems to be causing problems.

### ISSUE THREAD

**Issue by jihyundotkim** [gluestack/gluestack-ui#1068]
### Description

Lucide Icons seems to be a problem in `InputIcon`

### Steps to reproduce

Using Lucide Icons in `InputIcon` seems to cause a problem with because of 'sm' string somewhere.

```
<Input>
    <InputIcon>
        <Icon as={TruckIcon} />
    </InputIcon>
    <InputField />
</Input>
```

`<Icon as={TruckIcon} />` outside of `InputIcon` seems fine.

Gluestack icons such as 
```
<Input>
    <InputIcon>
        <Icon as={AddIcon} />
    </InputIcon>
    <InputField />
</Input>
```
seems to be alright.

### gluestack-ui Version

themed@0.1.38

### Platform

- [ ] Expo
- [X] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

### Other Platform

`lucide-react-native@0.276.0`

### Additional Information

The problem is more severe in Android; on iOS I get a warning in the Metro terminal `(ADVICE) "sm" is not a valid dimension. Dimensions must be a number, "auto", or a string suffixed with "%".` and the input icon doesn't show up but it does run.

On Android, the build "succeeds" but then I get this 

<img width="409" alt="android emulator error" src="https://github.com/gluestack/gluestack-ui/assets/54026908/d0b0cd3e-a791-464e-a43b-a25e685ab858">

log in Android Studio
```
Unknown value: sm
Exception in native call
java.lang.NumberFormatException: For input string: "sm"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:543)
	at java.lang.Double.valueOf(Double.java:506)
	at com.horcrux.svg.SVGLength.<init>(SVGLength.java:90)
	at com.horcrux.svg.SVGLength.from(SVGLength.java:107)
	at com.horcrux.svg.SvgView.setBbWidth(SvgView.java:225)
	at com.horcrux.svg.SvgViewManager.setBbWidth(SvgViewManager.java:155)
	at com.horcrux.svg.SvgViewManager.setBbWidth(SvgViewManager.java:32)
	at com.facebook.react.viewmanagers.RNSVGSvgViewManagerDelegate.setProperty(RNSVGSvgViewManagerDelegate.java:27)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:46)
	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:84)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

looked into the files in `themed/build/components/Icons/styled-components` as well as `icon/src` but couldn't figure out what exactly the problem was. Will do some more

**Comment by surajahmed** [comment]
@jihyundotkim Thanks for reporting this issue. We're working on it.

**Comment by jacargentina** [comment]
Maybe related with #951

**Comment by makkarMeenu** [comment]
This icon issue has been fixed in the latest version of `@gluestack-ui/themed`.
API of Input has been changed a bit
 from
```
<Input>    //View
 <InputField />   //TextInput
 <InputIcon>  //Pressable
    <Icon as={} />  //icon
</InputIcon>
</Input>
```
to

```
<Input>  //View
 <InputField />  //TextInput
 <InputSlot> //Pressable
     <InputIcon as={}/> //Icon
 </InputSlot>
</Input>
```

Let us know if you face any issue.

**Comment by jacargentina** [comment]
@makkarMeenu I'm getting this very same error with Radio

```jsx
        <RadioGroup ml="$2" value={tempResultShape} onChange={(v) => setTempResultShape(v)}>
          <Radio value="normal" my="$2" aria-label="normal">
            <RadioIndicator mr="$2">
              <RadioIcon as={CircleIcon} />
            </RadioIndicator>
            <RadioLabel>Normal</RadioLabel>
          </Radio>
          <Radio value="porProveedor" my="$2" aria-label="porProveedor">
            <RadioIndicator mr="$2">
              <RadioIcon as={CircleIcon} />
            </RadioIndicator>
            <RadioLabel>Por Proveedor</RadioLabel>
          </Radio>
        </RadioGroup>

```

<img width="346" alt="Captura de pantalla 2023-09-17 a la(s) 20 04 56" src="https://github.com/gluestack/gluestack-ui/assets/517228/dee9534e-a6fe-4802-b646-dbe2bdc13fea">
