### ISSUE TITLE
git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by franscal7** [gluestack/gluestack-ui#166]
GitError: Cloning into 'C:\Users\frans/.gluestack/cache/gluestack-ui'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at Object.action (C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\simple-git\dist\cjs\index.js:1274:25)
    at PluginStore.exec (C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\simple-git\dist\cjs\index.js:1309:29)
    at C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\simple-git\dist\cjs\index.js:1676:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\simple-git\dist\cjs\index.js:1674:16)
    at GitExecutorChain.<anonymous> (C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\simple-git\dist\cjs\index.js:1658:44)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\simple-git\dist\cjs\index.js:55:24) {
  task: {
    commands: [
      'clone',
      'git@github.com:gluestack/gluestack-ui.git',
      'C:\\Users\\frans/.gluestack/cache/gluestack-ui'
    ],
    format: 'utf-8',
    parser: [Function: parser]
  }
}
WARNING: gluestack/ui react installer is currently not available. Please configure it manually in your project.
Error: ENOENT: no such file or directory, open 'C:\Users\frans\source\organization-86\project-3-front/gluestack-ui.config.ts'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at componentAdder (C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\gluestack-ui\component-adder\index.js:172:27)
    at main (C:\Users\frans\AppData\Local\npm-cache\_npx\17e7bc1abc5c95a0\node_modules\gluestack-ui\index.js:14:11) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\frans\\source\\organization-86\\project-3-front/gluestack-ui.config.ts'
}

**Comment by Viraj-10** [comment]
hey @franscal7, Can elaborate more on this issue?
When are you getting this issue?

**Comment by franscal7** [comment]
Hi, I receive that error when I use `npx gluestack-ui` in my project react native 0.71.4 (I am using windows)

**Comment by palcisto** [comment]
@franscal7 Have you by chance changed your local SSH key on your computer lately and forgotten to update it in your Github profile?

Also, make sure you've added Github's SSH key fingerprints to your `known_hosts` file.

Here's a couple of resources I found today when I ran into a similar issue, the second article will help guide you on updating your `known_hosts` file on Windows while the first article lists Github's SSH key fingerprints:
* https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
* https://kinsta.com/knowledgebase/warning-remote-host-identification-has-changed/

**Comment by GollyJer** [comment]
This might help.
https://github.com/gluestack/gluestack-ui/issues/247

**Comment by mayank-96** [comment]
Hey @franscal7, this issue is fixed with latest version of `gluestack-ui`. Closing this issue please feel free to reopen it.
