### ISSUE TITLE
ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by maximedeoliveira** [gluestack/gluestack-ui#1685]
### Description

I'm trying to start a new NextJs project using gluestack. I build the project with the command `npm create gluestack`, but when I build the project, I have the following error 

```
⨯ node_modules/@expo/html-elements/build/elements/Headings.js (25:0) @ eval
⨯ ReferenceError: __DEV__ is not defined
  at __webpack_require__ (/Users/mdeoliveira/lab/gluestack-nextjs-repro/.next/server/webpack-runtime.js:33:42)
  at __webpack_require__ (/Users/mdeoliveira/lab/gluestack-nextjs-repro/.next/server/webpack-runtime.js:33:42)
  at __webpack_require__ (/Users/mdeoliveira/lab/gluestack-nextjs-repro/.next/server/webpack-runtime.js:33:42)
  at __webpack_require__ (/Users/mdeoliveira/lab/gluestack-nextjs-repro/.next/server/webpack-runtime.js:33:42)
  at eval (./app/providers.tsx:7:78)
  at (ssr)/./app/providers.tsx (/Users/mdeoliveira/lab/gluestack-nextjs-repro/.next/server/app/page.js:162:1)
  at __webpack_require__ (/Users/mdeoliveira/lab/gluestack-nextjs-repro/.next/server/webpack-runtime.js:33:42)
```

### CodeSandbox/Snack link

https://github.com/maximedeoliveira/gluestack-nextjs-repro

### Steps to reproduce

1. Create a new project with `npm create gluestack`
2. Select `NextJs app`
3. Select `Yes`, when ask about the app router
4. Run `npm run dev` to start the project

### gluestack-ui Version

latest

### Platform

- [ ] Expo
- [ ] React Native CLI
- [X] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by riverage-nada** [comment]
The same thing is happening when I select pages router

**Comment by rajat693** [comment]
hi @maximedeoliveira, we have released the new version of `@gluestack/ui-next-adapter: 2.1.11` , please update to the new latest version. This will resolve your issue.
