### ISSUE TITLE
eject library throws error within a monorepo

### ISSUE THREAD

**Issue by macrozone** [gluestack/gluestack-ui#1912]
### Description

ejecting the library throws an error in a monorepo

### Steps to reproduce

1. requires a monorepo where your gluestack components live within a sub package
2. execute `npx gluestack-ui-scripts eject`
3. it will show this:

```

$ npx gluestack-ui-scripts eject
┌  gluestack-ui-scripts
hello 2
⏳ Ejecting Components & Theme will copy all the themed components inside './components' folder.

 If you have already ejected the theme or components,
- This will overwrite the existing styles with default one. (It is NOT RECOMMENDED to eject again)
- If you need to eject the components, then save the changes and copy/paste them manually.

 Commit you changes before ejecting, this command with update the imports!!

 If you are already using @gluestack-ui/themed inside your project, running this command will automatically change the imports from @gluestack-ui/themed to the components folder path.
│
◇  Are you sure you want to continue?
│  Yes
│
◇  Enter folder name where you want ejected components.
│  gluestack
│
◇  How do you want to import the components?
│  Relative Path
⏳ Ejecting Components & Theme inside "gluestack". Please wait...
Error copying src folder: Error: Cannot find module '/path/to/project/libs/ui/node_modules/@gluestack-ui/config/package.json'
Require stack:
- /path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/scripts/eject-components/index.js
- /path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at /path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/scripts/eject-components/index.js:137:33
    at Generator.next (<anonymous>)
    at /path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/scripts/eject-components/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/scripts/eject-components/index.js:3:12)
    at installDependencies (/path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/scripts/eject-components/index.js:134:16) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/scripts/eject-components/index.js',
    '/path/to/.npm/_npx/124a6cf0cff875c9/node_modules/gluestack-ui-scripts/dist/index.js'
  ]
}
```

reason is that it tries to find `@gluestack-ui/conf` within the node_modules of the sub package, but in cases of monorepo it may live in the root's node_modules

### gluestack-ui Version

1.1.16

### Platform

- [X] Expo
- [ ] React Native CLI
- [X] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by macrozone** [comment]
workaround is to use it in the root, then manually moving the changes.

**Comment by vidhi499** [comment]
Hey @macrozone This issue is fixed with the latest release, try it out once using `npx gluestack-ui-scripts@latest eject`. Closing this issue, feel free to reopen it if you face any problem.

**Comment by vidhi499** [comment]
@macrozone On rejecting the components, the changes done by you on the ejected components will be lost, that's why it is not recommended. But if you want original ejected components, yes, you can re-eject.
