### ISSUE TITLE
gluestack starter for v2 not building

### ISSUE THREAD

**Issue by bidah** [gluestack/gluestack-ui#2439]
### Description

can't run the app

### CodeSandbox/Snack link

https://github.com/bidah/gluestack-v2-starter-issue

### Steps to reproduce

1. download reproducible repo with error https://github.com/bidah/gluestack-v2-starter-issue
2.  try to run app with `bun start` or `bun start -c`

getting this error:
```
TypeError: Cannot read properties of null (reading 'nativewind')
TypeError: Cannot read properties of null (reading 'nativewind')
    at /Users/rofi/Programing/gluestack-v2/node_modules/nativewind/src/metro/tailwind/v3/index.ts:75:19
    at Array.some (<anonymous>)
    at tailwindConfigV3 (/Users/rofi/Programing/gluestack-v2/node_modules/nativewind/src/metro/tailwind/v3/index.ts:74:37)
    at tailwindConfig (/Users/rofi/Programing/gluestack-v2/node_modules/nativewind/src/metro/tailwind/index.ts:17:28)
    at withNativeWind (/Users/rofi/Programing/gluestack-v2/node_modules/nativewind/src/metro/index.ts:33:39)
    at Object.<anonymous> (/Users/rofi/Programing/gluestack-v2/metro.config.js:16:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
error: script "start" exited with code 1
```

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

**Comment by Viraj-10** [comment]
Hey @bidah, Thanks for reporting the issue. We will have a look and get back to you.

**Comment by vaibhk20** [comment]
Hi @bidah, thank you for reporting the issue. We have updated our starter-kits for gluestack-ui v2 and the concerned issue should be resolved.
