### ISSUE TITLE
Error: Error: Command failed: npx jscodeshift -t

### ISSUE THREAD

**Issue by dribble-njr** [gluestack/gluestack-ui#2551]
### Description

Run `npx gluestack-ui init` occurs error.

### CodeSandbox/Snack link

https://github.com/dribble-njr/imperial-kitchen

### Steps to reproduce

1. Go to `apps/mobile`
2. Run `npx gluestack-ui init` 
3. See error

### gluestack-ui Version

lastest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [ ] Android
- [ ] iOS

### Additional Information

Environment:

```
node: 20.10.0
yarn: 1.22.22
```

**Comment by Viraj-10** [comment]
Hey @dribble-njr, Please try now we have updated our cli. 
If it doesn't work please report back to us with which operating system you are using.

**Comment by dribble-njr** [comment]
macOS 13.2.1 (22D68)

@Viraj-10 

```bash
➜  mobile git:(master) ✗ npx gluestack-ui init                               
Need to install the following packages:
gluestack-ui@0.7.20
Ok to proceed? (y) y

Welcome to gluestack-ui!

│
◇  Detected an Expo project, continue?
│  Yes

  ┌──────────────────────────────────────────────────────────────────────────────────────────┐
  │                                                                                          │
  │  NOTE: Files to get modified                                                             │
  │                                                                                          │
  │  The command you've run is attempting to modify certain files in your project,           │
  │  if already exist. Here's what's happening:                                              │
  │                                                                                          │
  │  - babel.config.js                                                                       │
  │  - metro.config.js                                                                       │
  │  - tailwind.config.*                                                                     │
  │  - global.css                                                                            │
  │  - tsconfig.json                                                                         │
  │                                                                                          │
  └──────────────────────────────────────────────────────────────────────────────────────────┘
  
│
◇  Proceed with caution. Make sure to commit your changes before proceeding. Continue?

│  Yes

Initializing gluestack-ui v2...

│
◇  Cloning successful.
warning package.json: No license field
│
○  ⏳ Installing dependencies. This might take a couple of minutes
yarn add v1.22.22
warning package.json: No license field
[1/4] 🔍  Resolving packages...
error TypeError [ERR_INVALID_URL]: Invalid URL
    at Url.parse (node:url:416:17)
    at Object.urlParse [as parse] (node:url:141:13)
    at module.exports.module.exports (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:72397:21)
    at urlParts (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:31663:75)
    at NpmRegistry.isRequestToRegistry (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:31706:19)
    at NpmRegistry.<anonymous> (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:31738:31)
    at Generator.next (<anonymous>)
    at step (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:328:14
    at new Promise (<anonymous>)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn add v1.22.22
warning package.json: No license field
[1/4] 🔍  Resolving packages...
error TypeError [ERR_INVALID_URL]: Invalid URL
    at Url.parse (node:url:416:17)
    at Object.urlParse [as parse] (node:url:141:13)
    at module.exports.module.exports (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:72397:21)
    at urlParts (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:31663:75)
    at NpmRegistry.isRequestToRegistry (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:31706:19)
    at NpmRegistry.<anonymous> (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:31738:31)
    at Generator.next (<anonymous>)
    at step (/Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/njr/.npm_global/lib/node_modules/yarn/lib/cli.js:328:14
│
◇  Dependencies have been installed successfully.
│
○  ⏳ Generating project configuration. This might take a couple of minutes
env: node\r: No such file or directory
│
■  Error occured in init. (Error: Command failed: npx jscodeshift -t /Users/njr/.npm/_npx/17e7bc1abc5c95a0/node_modules/gluestack-ui/template/codemods/expo/metro-config-transform.ts  /Users/njr/open-source/imperial-kitchen/apps/mobile/metro.config.js --cssPath=./global.css --isSDK50=true
│  env: node\r: No such file or directory
│  )
```

**Comment by TomSwift** [comment]
Same issue.

**Comment by rogerrc12** [comment]
Same issue here.. any updates?

**Comment by Sanchitv3** [comment]
Thanks for reporting!

This is no longer applicable with the current version of the codebase.

Closing for now, please open a new issue if it still persists 🙌
