### ISSUE TITLE
Please don't mutate package.json

### ISSUE THREAD

**Issue by FezVrasta** [gluestack/gluestack-ui#2577]
### Description

I'm using Yarn and using `yarn patch` to patch packages, but your postinstall script keeps adding `patch-package` to my scripts.

### Problem Statement

Please don't mutate the package.json, or at least provide a way to disable this behavior.

### Proposed Solution or API

Just ask users to edit it manually.

**Comment by DennisHesler** [comment]
My app is not working after modifying package.json

I changed my babel and webpack configuration and managed to launch the app, but not all the components work, eg the menu:

`MenuItem.tsx:62 Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at MenuItem (MenuItem.tsx:62:11)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (`

**Comment by Viraj-10** [comment]
@FezVrasta, you can shift to `@gluestack-ui/nativewind-utils@alpha` that way you can avoid change in `package.json`. Soon this will come to stable version.

**Comment by Viraj-10** [comment]
@DennisHesler Please create a another issue with repo.

**Comment by FezVrasta** [comment]
> @FezVrasta, you can shift to `@gluestack-ui/nativewind-utils@alpha` that way you can avoid change in `package.json`. Soon this will come to stable version.

Does this still require patching the other packages or it works with the non-patched dependencies?
