### ISSUE TITLE
Error when run ```npx gluestack-ui@latest```

### ISSUE THREAD

**Issue by NandoMB** [gluestack/gluestack-ui#286]
```sh
npx gluestack-ui@latest
 
gluestack/ui is not initialised in your project! 
✔ Do you wish to initialise it? (y/n)  … y
✔ Enter folder name where you want to add your components … components
/ Pulling changes...  
Failed to pull the changes. 
GitError: error: cannot lock ref 'refs/remotes/origin/patch': is at cc7e1a152a7ec4fb6f510aacdec0cac10cb15a24 but expected 75373a73ef952a0df599c0fa83185864171dfa9d
From github.com:gluestack/gluestack-ui
 ! 75373a73..6adc1a1d  patch      -> origin/patch  (unable to update local ref)

    at Object.action (/Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1274:25)
    at PluginStore.exec (/Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1309:29)
    at /Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1676:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1674:16)
    at GitExecutorChain.<anonymous> (/Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1658:44)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:55:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  task: {
    commands: [ 'pull' ],
    format: 'utf-8',
    parser: [Function: parser],
    onError: [Function: onError]
  }
}
\ Installing dependencies... Dependencies installed successfully.
Error: ENOENT: no such file or directory, open '/Volumes/Dados/Fernando/Development/study-gluestackui-3/gluestack-ui.config.ts'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at componentAdder (/Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/component-adder/index.js:156:27)
    at main (/Users/fernando/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/index.js:14:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Volumes/Dados/Fernando/Development/study-gluestackui-3/gluestack-ui.config.ts'
}
```

**Comment by AshwiniKumar007** [comment]
Hey @NandoMB ,
This shouldn’t happen. Will check this.

**Comment by mayank-96** [comment]
Hey @NandoMB , this issue has been fixed with the latest version of `gluestack-ui`. I am closing this issue for now. Please feel free to reopen it if you face this problem again. Thank you!

**Comment by BhuwaneshSisodia** [comment]
`npx gluestack-ui@latest init

node:internal/validators:163
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.dirname (node:path:1280:5)
    at Object.<anonymous> (/Users/bs-amazon/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/component-adder/utils.js:17:30)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v19.8.1`

**Comment by BhuwaneshSisodia** [comment]
```
`npx gluestack-ui@latest init

node:internal/validators:163
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.dirname (node:path:1280:5)
    at Object.<anonymous> (/Users/bs-amazon/.npm/_npx/4d3bda48cf361d69/node_modules/gluestack-ui/component-adder/utils.js:17:30)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v19.8.1`
```
