### ISSUE TITLE
[CLI] npx gluestack-ui@latest init fails

### ISSUE THREAD

**Issue by atanaskanchev** [gluestack/gluestack-ui#291]
Is there a way to setup a project without the cli? So far it hasn't been a smooth sailing

```shell
npx gluestack-ui@latest init
✔ Enter folder name where you want to add your components … components
| Pulling changes...
Failed to pull the changes.
GitError: error: cannot lock ref 'refs/remotes/origin/patch': is at cc7e1a152a7ec4fb6f510aacdec0cac10cb15a24 but expected 1d0a93885c4909914414d208a6443f9860e6f196
From github.com:gluestack/gluestack-ui
 ! 1d0a9388..e2c47244  patch      -> origin/patch  (unable to update local ref)

    at Object.action (/Users/atanas/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1274:25)
    at PluginStore.exec (/Users/atanas/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1309:29)
    at /Users/atanas/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1676:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/Users/atanas/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1674:16)
    at GitExecutorChain.<anonymous> (/Users/atanas/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:1658:44)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/atanas/.npm/_npx/4d3bda48cf361d69/node_modules/simple-git/dist/cjs/index.js:55:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  task: {
    commands: [ 'pull' ],
    format: 'utf-8',
    parser: [Function: parser],
    onError: [Function: onError]
  }
}
| Installing dependencies... node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: []
}

Node.js v18.15.0
```

**Comment by AshwiniKumar007** [comment]
Hey @atanaskanchev ,
Thanks for reporting. Will look into this.

**Comment by mayank-96** [comment]
Duplicate issue #286

**Comment by Black-Death-313** [comment]
Having this issue when trying to add gluestack-ui to my expo project [

 Initializing gluestack-ui v2...
|
o  Repository already cloned.
|
0  ⏳ Pulling latest changes..
|
x  Error: fetch-pack: invalid index-pack output
|
•  ⏳ Pulling latest changes.     Attempt 1)
|
x  Error: fetch-pack: invalid index-pack output
|
o  ⏳ Pulling latest changes..    Attempt 2)
|
x  Error: fetch-pack: invalid index-pack output
|
o  Pulling failed!
|
x   Cloning failed.
|
x  Error occured in init. (Error: Error pulling remote branch!) ]
