### ISSUE TITLE
using npx to install partial component cause infinite import error.

### ISSUE THREAD

**Issue by jasonz1360** [gluestack/gluestack-ui#456]
### Description

using npx to install partial component cause infinite import error.

### Steps to reproduce

1.  npx gluestack-ui@latest add ...
2.  in components/ foler index.ts,   `export * from './';` auto inserted.
3. run yarn expo:web to start server.
4.  open chrome inspector console.
5. See error
Uncaught RangeError: Maximum call stack size exceeded
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)
    at Module.GluestackUIProvider (index.tsx:9:1)

### gluestack-ui Version

0.1.2

### Platform

- [ ] Android
- [X] Expo
- [ ] iOS
- [ ] Next

**Comment by jasonz1360** [comment]
I can fix it by manually removing the line  `export * from './';`, just a little annoying.

**Comment by akash3gtm** [comment]
Hi @jasonz1360 , thank you for bringing this to our attention, we will look into this.

**Comment by makkarMeenu** [comment]
Please update gluestack-ui to the latest version and try. It will resolve the issue.
