### ISSUE TITLE
Problems Execute RN CLI

### ISSUE THREAD

**Issue by featlast** [gluestack/gluestack-ui#841]
### Description

Problems a execute run android

### Steps to reproduce

2. Click on '...' 
3. Scroll down to '...' 

### gluestack-ui Version

latest now

### Platform

- [X] Android
- [ ] Expo
- [ ] iOS
- [ ] Next

### Additional Information

Erros:
$ npx react-native run-android
info JS server already running.
info Installing the app...

FAILURE: Build failed with an exception.

* What went wrong:
Included build 'C:\Users\USUARIO\Desktop\pruebaupdate\node_modules\@react-native\gradle-plugin' does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Included build 'C:\Users\USUARIO\Desktop\pruebaupdate\node_modules\@react-native\gradle-plugin' does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (C:\Users\USUARIO\Desktop\pruebaupdate\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\USUARIO\Desktop\pruebaupdate\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (C:\Users\USUARIO\Desktop\pruebaupdate\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (C:\Users\USUARIO\Desktop\pruebaupdate\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.

**Comment by makkarMeenu** [comment]
This issue has no activity. Feel free to re-open if it still exists.
